# Generated by Django 6.0.3 on 2026-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre_tratamiento', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada_minutos', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientoProducto',
            fields=[
                ('id_tratamiento_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tratamiento_producto',
                'managed': False,
            },
        ),
    ]
