# Generated by Django 6.0.3 on 2026-04-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
