# Generated by Django 6.0.3 on 2026-04-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0002_alter_estado_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='secretaria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
