# Generated by Django 6.0.3 on 2026-04-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0003_alter_estado_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secretaria',
        ),
    ]
