# Generated by Django 6.0.3 on 2026-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0004_delete_secretaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'secretaria',
                'managed': False,
            },
        ),
    ]
