# Generated by Django 6.0.3 on 2026-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # FIX: sin esta dependencia explícita, Django no sabe que InventarioApp
    # ya tuvo (y borró) su propio modelo Empresa con db_table='empresa'.
    # Sin esto, esta migración puede correr ANTES de que InventarioApp
    # termine de crear y eliminar su tabla 'empresa', chocando con un
    # CREATE TABLE duplicado en la misma tabla física.
    dependencies = [
        ('InventarioApp', '0005_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('es_proveedor', models.BooleanField(default=True, verbose_name='¿Es Proveedor?')),
                ('es_comprador', models.BooleanField(default=False, verbose_name='¿Es Comprador?')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
    ]