# Generated by Django 6.0.3 on 2026-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('es_proveedor', models.BooleanField(default=True, verbose_name='¿Es Proveedor?')),
                ('es_comprador', models.BooleanField(default=False, verbose_name='¿Es Comprador?')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
    ]
