# Generated by Django 6.0.3 on 2026-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('diagnostico', models.TextField()),
                ('tratamiento_realizado', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('rh', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_preexistentes', models.TextField(blank=True, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
    ]
