"""
Django settings for odontoclinick project.

Generated by 'django-admin startproject' using Django 6.0.2.
Adaptado para despliegue en Railway (producción) y desarrollo local.
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SEGURIDAD
# =============================================================================

# La SECRET_KEY ahora viene de una variable de entorno. En local, se lee de
# tu archivo .env (que nunca se sube a git). En Railway, se configura en el
# panel de Variables del servicio.
SECRET_KEY = config('SECRET_KEY')

# DEBUG=False por defecto. En local pones DEBUG=True en tu .env.
# CRÍTICO: en producción (Railway) esto debe ser False, o Django expone
# tracebacks completos (incluyendo rutas del servidor y variables) a
# cualquiera que provoque un error 500.
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS viene de una variable de entorno, separada por comas.
# Railway asigna un dominio tipo *.up.railway.app — lo agregamos abajo
# automáticamente además de lo que pongas en la variable.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Railway expone el dominio público en esta variable de entorno automática.
# La agregamos a ALLOWED_HOSTS sin que tengas que escribirla a mano.
RAILWAY_PUBLIC_DOMAIN = config('RAILWAY_PUBLIC_DOMAIN', default='')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Necesario para que Django confíe en peticiones POST (formularios, login)
# que llegan a través del dominio HTTPS de Railway. Sin esto, vas a ver
# errores de "CSRF verification failed" en producción aunque todo esté bien.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')

# Railway sirve todo detrás de un proxy HTTPS. Esto le dice a Django que
# confíe en el header que indica que la conexión original era HTTPS,
# para que url-building, cookies seguras, etc. funcionen bien.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Solo forzar HTTPS y cookies seguras cuando NO estás en modo debug local.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'data_wizard',
    'data_wizard.sources',
    'rest_framework',
    'Webapp',            # La página principal
    'CuentasApp',        # Usuarios y Roles
    'PacienteApp',       # Fichas de pacientes
    'MedicoApp',         # Doctores y Horarios
    'CitaApp',           # Gestión de citas
    'TratamientoApp',    # Servicios y procedimientos
    'InventarioApp',     # Stock de insumos
    'FacturacionApp',    # Pagos y recibos
    'EmpresaApp',        # Empresas
    'AdminApp'           # Administración
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estáticos directamente desde Django en
    # producción, sin necesitar un servidor web aparte (nginx, etc.). Va
    # justo después de SecurityMiddleware, como indica su documentación.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# =============================================================================
# BASE DE DATOS
# =============================================================================
# Railway, al añadir el plugin de MySQL, inyecta automáticamente una variable
# de entorno MYSQL_URL (o DATABASE_URL según el plugin) con todo dentro:
# usuario, password, host, puerto, nombre de la base. dj_database_url la
# parsea directamente, así que no hay que copiar cada dato a mano.
#
# En LOCAL, como no tienes esa variable, usamos los valores sueltos de tu
# .env (DB_NAME, DB_USER, etc.) como respaldo.

DATABASE_URL = config('DATABASE_URL', default='') or config('MYSQL_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,  # Railway maneja la red internamente, no exige SSL entre servicios
        )
    }
    DATABASES['default']['OPTIONS'] = {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='odontoclinick'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = False

SITE_ID = 1

DATA_WIZARD = {
    'BACKEND': 'data_wizard.backends.threading',
    'LOADER': 'data_wizard.loaders.FileLoader',
    'IDMAPPER': 'data_wizard.idmappers.ModelIDMapper',
    'PARSERS': [
        'data_wizard.parsers.CSVParser',
    ],
}


# =============================================================================
# ARCHIVOS ESTÁTICOS (CSS, JS) — servidos por WhiteNoise en producción
# =============================================================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Carpeta donde `collectstatic` reúne todo para producción. WhiteNoise sirve
# los archivos desde aquí. Este directorio NO se sube a git (está en
# .gitignore) — Railway lo genera en cada deploy al correr collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Comprime y le pone hash al nombre de cada archivo estático (cache-busting
# automático: si cambias un CSS, el navegador no sirve la versión vieja
# cacheada).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =============================================================================
# ARCHIVOS MULTIMEDIA (fotos, QR codes, comprobantes)
# =============================================================================
# ADVERTENCIA IMPORTANTE: Railway NO tiene almacenamiento persistente por
# defecto. Cualquier archivo guardado aquí (incluyendo los QR de citas que
# genera el modelo Cita) se BORRA en cada redeploy. Esto requiere una
# solución aparte (almacenamiento en la nube tipo S3/Cloudinary, o un
# volumen de Railway). Lo resolvemos en un paso posterior — por ahora dejamos
# la configuración local funcionando para que el resto del deploy no se
# bloquee.

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# EMAIL (SMTP) — credenciales ahora vía variable de entorno
# =============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


# =============================================================================
# AUTENTICACIÓN
# =============================================================================

AUTH_USER_MODEL = 'CuentasApp.Usuario'
LOGIN_URL = '/cuentas/login/'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# =============================================================================
# TWILIO (SMS) — credenciales ahora vía variable de entorno
# =============================================================================

TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_NUMBER = config('TWILIO_NUMBER')
