# Generated by Django 6.0.3 on 2026-06-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CitaApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('es_proveedor', models.BooleanField(default=True, verbose_name='¿Es Proveedor?')),
                ('es_comprador', models.BooleanField(default=False, verbose_name='¿Es Comprador?')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.IntegerField(verbose_name='Precio de Venta Base')),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('ML', 'Mililitros'), ('GR', 'Gramos'), ('CJ', 'Caja')], default='UN', max_length=2)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='InventarioApp.categoriaproducto')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ajuste)'), ('SALIDA', 'Salida (Consumo/Pérdida)')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, null=True)),
                ('precio_transaccion', models.IntegerField(blank=True, help_text='Precio cobrado o pagado por unidad', null=True)),
                ('cliente_externo', models.ForeignKey(blank=True, db_column='id_cliente_externo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_materiales_personales', to=settings.AUTH_USER_MODEL)),
                ('empresa_asociada', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioApp.empresa')),
                ('id_cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_consumidos', to='CitaApp.cita')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_operados', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.producto')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'managed': True,
            },
        ),
    ]
