# Generated by Django 6.0.3 on 2026-04-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UN', 'Unidad'), ('ML', 'Mililitros'), ('GR', 'Gramos'), ('CJ', 'Caja')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ajuste)'), ('SALIDA', 'Salida (Consumo/Pérdida)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='InventarioApp.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
