# Generated by Django 6.0.3 on 2026-06-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEmpresa',
            fields=[
                ('id_producto_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('precio_compra_proveedor', models.IntegerField(verbose_name='Precio de Compra de este Proveedor')),
                ('stock_proveedor', models.IntegerField(default=0, verbose_name='Stock disponible de este proveedor')),
                ('fecha_ultimo_abastecimiento', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_lotes', to='InventarioApp.producto')),
            ],
            options={
                'db_table': 'producto_empresa',
                'managed': True,
                'unique_together': {('id_producto', 'id_empresa', 'precio_compra_proveedor')},
            },
        ),
    ]
