# Generated by Django 4.2.23 on 2026-06-18 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventarioApp', '0002_producto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientoinventario',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
