# Generated by Django 6.0.3 on 2026-06-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaApp', '0001_initial'),
        ('InventarioApp', '0003_movimientoinventarioidcita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoempresa',
            name='id_empresa',
            field=models.ForeignKey( db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='EmpresaApp.empresa',
            ),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='empresa_asociada',
            field=models.ForeignKey( blank=True, null=True, db_column='id_empresa', on_delete=django.db.models.deletion.SET_NULL, to='EmpresaApp.empresa',
            ),
        ),
    ]
