# Generated by Django 6.0.3 on 2026-06-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0004_alter_productoempresa_id_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
