# Generated by Django 6.0.3 on 2026-06-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaApp', '0001_initial'),
        ('InventarioApp', '0005_delete_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario_salida',
            field=models.IntegerField(blank=True, help_text='Costo promedio ponderado por unidad según lotes FIFO consumidos', null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='precio_transaccion',
            field=models.IntegerField(blank=True, help_text='Precio cobrado (SALIDA/venta) o pagado (ENTRADA/compra) por unidad', null=True),
        ),
        migrations.CreateModel(
            name='LoteCompra',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('precio_compra', models.IntegerField(verbose_name='Precio pagado por unidad en esta compra')),
                ('cantidad_inicial', models.IntegerField(verbose_name='Unidades compradas en este lote')),
                ('cantidad_disponible', models.IntegerField(verbose_name='Unidades aún no vendidas de este lote')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_proveidos', to='EmpresaApp.empresa')),
                ('id_movimiento_entrada', models.OneToOneField(blank=True, help_text='El MovimientoInventario ENTRADA que creó este lote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_generado', to='InventarioApp.movimientoinventario')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='InventarioApp.producto')),
            ],
            options={
                'db_table': 'lote_compra',
                'ordering': ['fecha_compra'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Unidades tomadas de este lote')),
                ('precio_compra', models.IntegerField(verbose_name='Precio de compra al momento de la salida (snapshot)')),
                ('id_movimiento', models.ForeignKey(db_column='id_movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_lote', to='InventarioApp.movimientoinventario')),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='InventarioApp.lotecompra')),
            ],
            options={
                'db_table': 'detalle_salida',
                'managed': True,
            },
        ),
    ]
