# Generated by Django 6.0.3 on 2026-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('notas_paciente', models.TextField(blank=True, null=True)),
                ('notas_doctor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitaTratamiento',
            fields=[
                ('id_cita_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('costo_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('completado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cita_tratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estado_cita',
                'managed': False,
            },
        ),
    ]
