# Generated by Django 6.0.3 on 2026-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
            ],
            options={
                'db_table': 'estado_cita',
            },
        ),
    ]
