# Generated by Django 6.0.3 on 2026-06-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CitaApp', '0001_initial'),
        ('MedicoApp', '0001_initial'),
        ('PacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicoApp.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PacienteApp.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_estado_cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CitaApp.estadocita'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('id_doctor', 'fecha_hora')},
        ),
    ]
