# Generated by Django 6.0.3 on 2026-04-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CitaApp', '0001_initial'),
        ('MedicoApp', '0001_initial'),
        ('PacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(db_column='id_doctor', on_delete=django.db.models.deletion.DO_NOTHING, to='MedicoApp.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='PacienteApp.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_estado_cita',
            field=models.ForeignKey(db_column='id_estado_cita', on_delete=django.db.models.deletion.DO_NOTHING, to='CitaApp.estadocita'),
        ),
    ]
