# Generated by Django 6.0.3 on 2026-04-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitaApp', '0002_initial'),
        ('MedicoApp', '0002_historialmedico_plan_tratamiento_and_more'),
        ('PacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estadocita',
            options={},
        ),
        migrations.AddField(
            model_name='cita',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicoApp.medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_estado_cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CitaApp.estadocita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PacienteApp.paciente'),
        ),
        migrations.AlterField(
            model_name='estadocita',
            name='color',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadocita',
            name='nombre_estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='cita',
            table=None,
        ),
        migrations.AlterModelTable(
            name='estadocita',
            table=None,
        ),
    ]
