# Generated by Django 6.0.3 on 2026-04-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitaApp', '0003_alter_cita_options_alter_estadocita_options_and_more'),
        ('MedicoApp', '0003_alter_historialmedico_costo_aplicado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('id_doctor', 'fecha_hora')},
        ),
        migrations.AlterModelTable(
            name='cita',
            table='cita',
        ),
        migrations.AlterModelTable(
            name='estadocita',
            table='estado_cita',
        ),
    ]
