# Generated by Django 4.2.23 on 2026-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitaApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
