# Generated by Django 4.2.23 on 2026-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitaApp', '0005_cita_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
