# Generated by Django 6.0.6 on 2026-06-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitaApp', '0006_cita_hora_llegada'),
        ('CitaApp', '0007_auto_20260621_0024'),
    ]

    operations = [
    ]
