# Generated by Django 6.0.3 on 2026-04-03 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CitaApp', '0001_initial'),
        ('TratamientoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('costo_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completado', models.BooleanField(default=True)),
                ('diagnostico', models.TextField()),
                ('observaciones_clinicas', models.TextField(blank=True, null=True)),
                ('notas_paciente', models.TextField(blank=True, null=True)),
                ('notas_doctor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='CitaApp.cita')),
                ('id_tratamiento', models.ForeignKey(db_column='id_tratamiento', on_delete=django.db.models.deletion.PROTECT, to='TratamientoApp.tratamiento')),
            ],
            options={
                'db_table': 'historial_medico',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('licencia_medica', models.CharField(blank=True, max_length=50, null=True)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='MedicoApp.especialidad')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='MedicoApp.medico')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'disponibilidad',
            },
        ),
    ]
