# Generated by Django 6.0.3 on 2026-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita_minutos', models.IntegerField()),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('licencia_medica', models.CharField(blank=True, max_length=50, null=True)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
    ]
