# Generated by Django 6.0.3 on 2026-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='plan_tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
