# Generated by Django 6.0.3 on 2026-04-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CitaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(max_length=50, unique=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.DO_NOTHING, to='CitaApp.cita')),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='FacturacionApp.metodopago')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
    ]
